=== alvarporcar/POW/src/report.dtd
<!--
  Report DTD for JFreeReport version 0.7.0.

	ChangeLog:

	2002-05-01: Taq: Added multiline-field and multiline-function element
  2002-05-23: Changed the font style for extended attributes. The old attribute is also valid
              and gets silently mapped to the new style by the parser.
  2002-06-09: Added the rectangle shape element
  2002-06-30: ImageField, ImageFunction
  2002-07-10: ImageURLField, ImageURLFunction
  2002-07-17: Updated missing attributes in Image* tags
 -->

<!ENTITY % boolean
   "true | false"
>

<!ENTITY % fontstyle
   "plain | bold | italic | bold-italic"
>

<!ENTITY % alignmentEnum
   "left | center | right"
>

<!--

 The position of an element is declared either relative to the last
 defined element in the band (or (0,0) if the element is the first element),
 or it is positioned absolute to the top left corner of the current band.

 When positioning an element be aware to take care of the elements width.
 The next element should be placed at the absolute position x+width,
 or the elements will overwrite each other.

 All Fontstyles default to plain and all boolean styles to false. If no font is
 set either in Band nor in element, a compiled in default font is used.

-->
<!ENTITY % position
 "x           CDATA          #IMPLIED
  y           CDATA          #IMPLIED
	x-rel       CDATA          #IMPLIED
	y-rel       CDATA          #IMPLIED
  width       CDATA          #REQUIRED"
>

<!--

  Colors are specified in HTML Syntax, so use #FFFFFF for white and #000000
  for black when using RGB numeric values. You may also use defined named
  constants for the color, as "black", "white" and so on.

  The constants understood by the parser are:
  "black", "blue", "cyan", darkGray", "gray", "green", "lightGray", "magenta",
  "orange", "pink", "red", "white", "yellow"

  -->
<!ENTITY % basicform
" height         CDATA          #REQUIRED
  color          CDATA          #IMPLIED
	name           CDATA          #IMPLIED"
 >

<!ENTITY % fontdef
" fontname       CDATA              #IMPLIED
  fontstyle      (%fontstyle;)      #IMPLIED
  fontsize       CDATA              #IMPLIED
  fsbold         (%boolean;)        #IMPLIED
  fsitalic       (%boolean;)        #IMPLIED
  fsunderline    (%boolean;)        #IMPLIED
  fsstrikethr    (%boolean;)        #IMPLIED
  alignment      (%alignmentEnum;)  #IMPLIED
  baseline       CDATA              #IMPLIED"
 >

<!--
  Removed multiline function: This element was never implemented and now all text elements
  support linebreaks.
  -->
<!ENTITY % itemelements
  "(label | general-field | string-field | string-function |
  number-field | number-function | date-field | date-function |
	multiline-field | imageref | image-field | image-function | rectangle | line)*">

<!--

     Colordefinitions are given either as predefined names as defined
     in HTML or as HTML-RGB-Color-Reference ("#rrggbb");

 -->


<!--

   A report constists of several elements, which are all optional:

   * reportheader
     printed at the first page

   * reportfooter
     printed on the last page

   * a page header
     Printed before any content is printed to the page.

   * a page footer
     printed, after the last content for the page is printed
     The pagefooter is always positionated at the bottom of a page,
     regardless how much space of the page is filled.

   * one or more group definitions in the "groups" element
     If no groups are defined, a default group is created to contain
     all data elements of the current report.

   * the (optional) item band. This is where the data rows are printed.
     If no item band is defined, only printing is disabled. All
     calculations are performed regardless of the appearance of the
     items.

   Attributes:
    Width  = the width of the report in Java-Printing-Units
    Height = the height of the report

    All printing units are defined in 1/72 inches, the default printing
    resolution on java.awt.graphics.

    minPageFormat = a predefined page format, for instance "A4" or "US-LETTER"


  -->

<!ENTITY % pageFormats
  "(  A | A0 | A1 | A10 | A2 | A3 | A4 | A5 | A6 | A7 | A8 | A9 | B | B0 | B1 | B10 |
    B2 | B3 | B4 | B5  | B6 | B7 | B8 | B9 | C | C0 | C1 | C10 | C2 | C3 | C4 | C5 |
    C6 | C7 | C8 | C9 | D  | E  | ENV_10 | ENV_10X13 | ENV_10X14 | ENV_10X15 | ENV_11 |
    ENV_12 | ENV_14 | ENV_6X9 | ENV_7X9 | ENV_9 | ENV_9X11 | ENV_9X12 | ENV_INVITE |
    ENV_ITALY  | ENV_MONARCH | ENV_PERSONAL | EXECUTIVE | FOLIO  | INVITE | INVITE_ENVELOPE |
    INVOICE | ISO_2A0 | ISO_4A0 | ISO_A0 | ISO_A1 | ISO_A10 | ISO_A2 | ISO_A3  | ISO_A4  |
    ISO_A5  | ISO_A6  | ISO_A7  | ISO_A8  | ISO_A9  | ISO_B0  | ISO_B1  | ISO_B10 | ISO_B2  |
    ISO_B3  | ISO_B4  | ISO_B4_ENVELOPE    | ISO_B5 | ISO_B5_ENVELOPE | ISO_B6 | ISO_B7 |
    ISO_B8 | ISO_B9 | ISO_C0 | ISO_C0_ENVELOPE | ISO_C1 | ISO_C1_ENVELOPE | ISO_C10 |
    ISO_C10_ENVELOPE  | ISO_C2 | ISO_C2_ENVELOPE | ISO_C3 | ISO_C3_ENVELOPE | ISO_C4 |
    ISO_C4_ENVELOPE | ISO_C5 | ISO_C5_ENVELOPE | ISO_C6 | ISO_C6_ENVELOPE | ISO_C7 |
    ISO_C7_ENVELOPE | ISO_C8 | ISO_C8_ENVELOPE | ISO_C9 | ISO_C9_ENVELOPE | ISO_DESIGNATED_LONG |
    ISO_DESIGNATED_LONG_ENVELOPE | ITALY | ITALY_ENVELOPE | JIS_B0 | JIS_B1 | JIS_B10  |
    JIS_B2  | JIS_B3  | JIS_B4  | JIS_B5  | JIS_B6  | JIS_B7  | JIS_B8  | JIS_B9  | LEDGER  |
    LEGAL   | LETTER  | MONARCH | MONARCH_ENVELOPE  | NA_10X13_ENVELOPE | NA_10X14_ENVELOPE |
    NA_10X15_ENVELOPE | NA_6X9_ENVELOPE   | NA_7X9_ENVELOPE   | NA_9X11_ENVELOPE  |
    NA_9X12_ENVELOPE | NA_LEGAL | NA_LETTER  | NA_NUMBER_10_ENVELOPE | NA_NUMBER_11_ENVELOPE |
    NA_NUMBER_12_ENVELOPE | NA_NUMBER_14_ENVELOPE | NA_NUMBER_9_ENVELOPE | NOTE | PERSONAL |
    PERSONAL_ENVELOPE | QUARTO  | STATEMENT | TABLOID ) "
>

<!ELEMENT report   (reportheader?, reportfooter?, pageheader?, pagefooter?, groups?, items?, functions?)>

<!ATTLIST report
  width          CDATA           #IMPLIED
  height         CDATA           #IMPLIED
  name           CDATA           #IMPLIED
  minpageformat  %pageFormats;   #IMPLIED
>


<!--

  The reportheader can contain any band-element.
  The height of the report header is ignored, if the header is
  printed on an own page.

  As with every element container you may define default font settings
  for sub elements without an own font definition.

  -->
<!ELEMENT reportheader ( %itemelements; )>
<!ATTLIST reportheader
  ownpage        (%boolean;)    #IMPLIED
  %basicform;
>

<!ELEMENT reportfooter ( %itemelements; )>
<!ATTLIST reportfooter
  ownpage        (%boolean;)    #IMPLIED
  %basicform;
>



<!--

  The pageheader can contain any band-element.

  As with every element container you may define default font settings
  for sub elements without an own font definition.

  -->
<!ELEMENT pageheader ( %itemelements; )>
<!ATTLIST pageheader
  onfirstpage    (%boolean;)   #IMPLIED
  %basicform;
>


<!ELEMENT pagefooter ( %itemelements; )>
<!ATTLIST pagefooter
  onfirstpage    (%boolean;)   #IMPLIED
  onlastpage     (%boolean;)   #IMPLIED
  %basicform;
>

<!--

  The tag encapsulates all groups. This tag helps to keep parsing
  simple. If no groups are defined, a default group has to be created
  containing all elements of the report data

  -->
<!ELEMENT groups (group+)>

<!ELEMENT group  (groupheader?, groupfooter?, fields+)>
<!ATTLIST group
  name           CDATA         #IMPLIED
>

<!--

  A group header is printed before a group starts. A group start
  is invoked when one element in groupelements changes and on the
  start of the report generation.

  If pagebreak is set to true, a page break will be forced before
  the group header is printed.

  -->
<!ELEMENT groupheader ( %itemelements; )>
<!ATTLIST groupheader
  pagebreak     (%boolean;)   #IMPLIED
  %basicform;
>

<!ELEMENT groupfooter ( %itemelements; )>
<!ATTLIST groupfooter
  %basicform;
>

<!--
  the name of the elements that have to change for
  a group break.

  A report group may have more than one group element.
  A group element may only contain Strings defining the
  names of the items which form a group. This is not
  limited to items from the data model, you may also
  enter functions here.

 -->
<!ELEMENT fields  (field*)>
<!ELEMENT field  (#PCDATA)>

<!ELEMENT items   ( %itemelements; )>
<!ATTLIST items
  %basicform;
>

<!--
  A simple label, static text that does not change
  -->
<!ELEMENT label   (#PCDATA)>
<!ATTLIST label
  %basicform;
  %position;
  %fontdef;
  nullstring  CDATA    #IMPLIED
>

<!--
  A generic field, currently this prints a string representation
  of the given object.
  -->
<!ELEMENT general-field EMPTY>
<!ATTLIST general-field
  %basicform;
  %position;
  %fontdef;
  fieldname   CDATA    #REQUIRED
>

<!--
  A simple text field without line break capability
  -->
<!ELEMENT string-field   EMPTY>
<!ATTLIST string-field
  %basicform;
  %position;
  %fontdef;
  fieldname   CDATA    #REQUIRED
  nullstring  CDATA    #IMPLIED
>

<!--
  A simple text field with line break capability
  -->
<!ELEMENT multiline-field   EMPTY>
<!ATTLIST multiline-field
  %basicform;
  %position;
  %fontdef;
  fieldname   CDATA    #REQUIRED
  nullstring  CDATA    #IMPLIED
>

<!ELEMENT number-field   EMPTY>
<!ATTLIST number-field
  %basicform;
  %position;
  %fontdef;
  format		CDATA      #IMPLIED
  fieldname   CDATA    #REQUIRED
  nullstring  CDATA    #IMPLIED
>

<!ELEMENT date-field   EMPTY>
<!ATTLIST date-field
  %basicform;
  %position;
  %fontdef;
  format		CDATA      #IMPLIED
  fieldname   CDATA    #REQUIRED
  nullstring  CDATA    #IMPLIED
>

<!--

  Function definition part 1. This defines a function reference,
  which is used to display the results of a certain function. If
  you want to reuse function results, then this feature is usefull,
  especially when calculating the results is expensive.

  -->
<!ELEMENT string-function   EMPTY>
<!ATTLIST string-function
  %basicform;
  %position;
  %fontdef;
  function    CDATA    #REQUIRED
  nullstring  CDATA    #IMPLIED
>

<!--

  @0.7.2 This on is not yet implemented. Next Release.
   ->    Removed, all TextElements support LineBreaks, there no need for a special function
         anymore

<!ELEMENT multiline-function   EMPTY>
<!ATTLIST multiline-function
  %basicform;
  %position;
  %fontdef;
  function    CDATA    #REQUIRED
  nullstring  CDATA    #IMPLIED
>
  -->

<!ELEMENT number-function   EMPTY>
<!ATTLIST number-function
  %basicform;
  %position;
  %fontdef;
  function    CDATA    #REQUIRED
  format		  CDATA    #IMPLIED
  nullstring  CDATA    #IMPLIED
>

<!ELEMENT date-function   EMPTY>
<!ATTLIST date-function
  %basicform;
  %position;
  %fontdef;
  function    CDATA    #REQUIRED
  format		  CDATA    #IMPLIED
  nullstring  CDATA    #IMPLIED
>

<!--

 This one was never implemented. Use a generic text function to display objects. The textfunction
 uses toString() to display the string representation, as this element was intended to do.

<!ELEMENT general-function   EMPTY>
<!ATTLIST general-function
  %basicform;
  %position;
  %fontdef;
  function    CDATA #REQUIRED
>
-->
<!--

   The image reference links an external image into the report.

  -->
<!ELEMENT imageref   EMPTY>
<!ATTLIST imageref
  %position;
  src         CDATA #REQUIRED
  height      CDATA #REQUIRED
  name        CDATA #REQUIRED
>
<!--

   The image reference links an external image into the report. This element expects an
   Graphics2D-Object in the datasource.

  -->
<!ELEMENT image-field   EMPTY>
<!ATTLIST image-field
  %position;
  field       CDATA #REQUIRED
  height      CDATA #REQUIRED
  name        CDATA #REQUIRED
>
<!--

   The image reference links an external image into the report. This element expects an
   Graphics2D-Object in the datasource.

  -->
<!ELEMENT image-function   EMPTY>
<!ATTLIST image-function
  %position;
  height      CDATA #REQUIRED
  function    CDATA #REQUIRED
  name        CDATA #REQUIRED
>
<!--

   The image reference links an external image into the report. This element expects an
   URL or URL-String in the datasource.

  -->
<!ELEMENT imageurl-field   EMPTY>
<!ATTLIST imageurl-field
  %position;
  height      CDATA #REQUIRED
  field       CDATA #REQUIRED
  name        CDATA #REQUIRED
>
<!--

   The image reference links an external image into the report. This element expects an
   URL or URL-String in the datasource.

  -->
<!ELEMENT imageurl-function   EMPTY>
<!ATTLIST imageurl-function
  %position;
  height      CDATA #REQUIRED
  function    CDATA #REQUIRED
  name        CDATA #REQUIRED
>


<!--

  Functions are defined in a function library.
  Every referenced function has to be defined in the
  library in order to be loaded and executed correctly.

  -->
<!ELEMENT functions  (function | data-ref)*>

<!--

  A data reference is used to validate the table model against
	the declared format of the datasource. It simply checks that
	all fields declared are present and are assignable from the
	given type.

	The attribute class is used to validate the data models objects.
	This function uses TableModel.getColumnClass() to query the
	table models data types. If the tablemodel returns java.lang.Object
	no check is done, java.lang.Object is considered as an indicator
	that the table model does not know about it's internal data
	structure.

	0.7.0 - This function will be implemented in the next release

-->
<!ELEMENT data-ref  EMPTY>
<!ATTLIST data-ref
  name    CDATA   #REQUIRED
	class   CDATA   #IMPLIED
>

<!--

  A defined function has a valid implementing class that implement
  the com.jrefinery.report.function.Function interface.

  Function parameters are given by propery elements. For visual
  editing, function must obey to the java-beans rules (use get*/set*
  methods, perhaps provide beaninfo and so on)

  -->
<!ELEMENT function   (properties?)>
<!ATTLIST function
  class      CDATA    #REQUIRED
	name       CDATA    #REQUIRED
>

<!ELEMENT properties  (property*)>

<!ELEMENT property    (#PCDATA)>
<!ATTLIST property
  name       CDATA    #REQUIRED
>


<!--

  Shapes

  -->
<!ELEMENT line      EMPTY>
<!ATTLIST line
  x1        CDATA       #REQUIRED
  y1        CDATA       #REQUIRED
  x2        CDATA       #REQUIRED
  y2        CDATA       #REQUIRED
	color     CDATA       #IMPLIED
	name      CDATA       #IMPLIED
	weight    CDATA       #IMPLIED
>

<!--

  The rectangle is a filled rectangular area. No outline is drawn.

  -->
<!ELEMENT rectangle EMPTY>
<!ATTLIST rectangle
  %position;
  %basicform;
>

=== alvarporcar/POW/bin/rAT1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!--
	<!DOCTYPE report SYSTEM "http://jfreereport.sourceforge.net/report.dtd">
-->
<report name="rAT1" width="0" height="0">

    <reportheader height="110" fontname="Serif" fontstyle="bold" fontsize="15" >
        <label name="Label 0" x="0" y="20" width="100%" height="5" alignment="center" fontstyle="bold" fontsize="9">Servicio P. Asesoramiento a Municipios (SEPAM)</label>
        <imageref x="0" y="0" width="80" height="30" src="p200apa.jpg" name="dipcasApaisatRoig"/>
        <line name="line0" x1="0" y1="35" x2="0" y2="35" weight="1"></line>
        <label name="Label 1" x="0" y="40" width="100%" height="20" baseline="20" color="#C71444" alignment="center" >ASISTENCIA TÉCNICA</label>
        <string-field name="descripcion" x="0" y="60" width="100%" height="10" alignment="center" fieldname="descripcion" color="#C71444"/>
        <string-field name="ano" x="5" y="75" width="10" fontsize="13" height="4" color="#C71444" fieldname="ano"/>
        <string-field name="mes" x="50" y="75" width="10" fontsize="13" height="4" color="#C71444" fieldname="mes"/>
        <line name="line5" x1="0" y1="100" x2="0" y2="100" color="lightGray" weight="10"></line>
    </reportheader>

    <reportfooter height="50" fontname="Serif" fontsize="8" fontstyle="bold">
        <line name="line6" x1="0" y1="10" x2="0" y2="10" weight="1"/>
        <number-function name="total1" function="Sum1" format="#,##0" x="190" y="20" width="76" height="20" alignment="right"></number-function>
        <number-function name="total2" function="Sum2" format="#,##0" x="240" y="20" width="76" height="20" alignment="right"></number-function>
        <number-function name="total3" function="Sum3" format="#,##0" x="280" y="20" width="76" height="20" alignment="right"></number-function>
        <number-function name="total4" function="Sum4" format="#,##0" x="330" y="20" width="76" height="20" alignment="right"></number-function>
    </reportfooter>

    <pageheader height="80" onfirstpage="false" fontname="Serif" fontstyle="bold" fontsize="10">
        <label name="Label 0" x="0" y="20" width="100%" height="5" alignment="center" fontstyle="bold" fontsize="9">Servicio P. Asesoramiento a Municipios (SEPAM)</label>
        <imageref x="0" y="0" width="80" height="30" src="p200apa.jpg" name="dipcasApaisatRoig"/>
        <line name="line0" x1="0" y1="35" x2="0" y2="35" weight="1"></line>
        <label name="label50" x="100" y="45" width="100%" height="10" color="#C71444" >Asistencia Técnica - Listado Mensual Ofisam</label>
        <string-field name="descripcion" x="0" y="55" width="100%" fontsize="12" color="#C71444" height="10" alignment="center" fieldname="descripcion" />
        <line name="line1" x1="0" y1="75" x2="0" y2="75" color="lightGray" weight="2"></line>
    </pageheader>

    <pagefooter height="24" onfirstpage="true" onlastpage="true" fontname="Serif" fontstyle="italic" fontsize="9">
        <line name="line2" x1="0" y1="4" x2="0" y2="4" weight="0.5"></line>
        <date-function name="date1" function="Date" format="d-MMM-yyyy" x="0" y="4" width="100" height="18" alignment="left"></date-function>
        <number-function name="pagenum1" function="PageNumber" format="Page 0" x="420" y="4" width="30" height="18" ></number-function>
    </pagefooter>


     <groups>
            <group name="AT1">
                    <groupheader height="25" fontname="Monospaced" fontstyle="bold" fontsize="8">
                            <label name="Label 11" x="2" y="1" width="50" height="10" >Expdte:</label>
                            <string-field name="expdte" x="45" y="1" width="100" alignment="left" height="10" fontstyle="bold" fieldname="expdte" />
                            <label name="Label 12" x="135" y="1" width="50" height="10" >Peticionario:</label>
                            <string-field name="peticionario" x="215" y="1" width="100" alignment="left" height="10" fontstyle="bold" fieldname="peticionario" />
                            <label name="Label 6" x="1" y="12" width="5" height="10" >Día</label>
                            <label name="Label 7" x="20" y="12" width="170" height="10" >Nombre</label>
                            <label name="Label 8" x="190" y="12" width="10" height="10" >Tipo</label>
                            <label name="Label 10" x="250" y="12" width="15" height="10" >Proy.</label>
                            <label name="Label 13" x="295" y="12" width="15" height="10" >Cert.</label>
                            <label name="Label 14" x="345" y="12" width="15" height="10" >Peri.</label>
                            <label name="Label 15" x="390" y="12" width="10" height="10" >Plan.</label>
                            <label name="Label 16" x="425" y="12" width="10" height="10" >Situ.</label>
                            <line name="line5" x1="0" y1="22" x2="0" y2="22" weight="1"/>
                    </groupheader>

                    <groupfooter height="20" fontname="Monospaced" fontstyle="bold" fontsize="9">

                    </groupfooter>

                     <fields>
                        <field>expdte</field>
                        <field>peticionario</field>
                     </fields>

            </group>
    </groups>

    <items height="10" fontname="Monospaced" fontstyle="plain" fontsize="6">
      <string-field name="dia" x="1" y="10"  width="5" height="10" fieldname="dia" />
      <string-field name="nombre" x="20" y="10" width="180" height="10" alignment="left" fieldname="nombre" />
      <string-field name="tipo" x="200" y="10"  width="50" height="10" fieldname="tipo" />
      <number-field name="proyectado" x="250" y="10" width="15" format="#,##0" alignment="right" height="10" fieldname="proyectado" />
      <number-field name="certificado" x="295" y="10" width="15" format="#,##0" alignment="right" height="10" fieldname="certificado" />
      <number-field name="peritado" x="340" y="10" width="15" format="#,##0" alignment="right" height="10" fieldname="peritado" />
      <number-field name="planos" x="390" y="10" width="15" format="#,##0" alignment="right" height="10" fieldname="planos" />
      <string-field name="situacion" x="430" y="10"  width="10" height="10" fieldname="situacion" />
    </items>

    <functions>

        <function name="Date" class="com.jrefinery.report.function.ReportPropertyFunction">
			<properties>
				<property name="reportProperty">report.date</property>
			</properties>
        </function>

        <function name="PageNumber" class="com.jrefinery.report.function.PageFunction"/>

      <function name="Sum1" class="com.jrefinery.report.function.ItemSumFunction">
         <properties>
           <property name="field">proyectado</property>
         </properties>
      </function>

      <function name="Sum2" class="com.jrefinery.report.function.ItemSumFunction">
         <properties>
           <property name="field">certificado</property>
         </properties>
      </function>

      <function name="Sum3" class="com.jrefinery.report.function.ItemSumFunction">
         <properties>
           <property name="field">peritado</property>
         </properties>
      </function>

      <function name="Sum4" class="com.jrefinery.report.function.ItemSumFunction">
         <properties>
           <property name="field">planos</property>
         </properties>
      </function>

    </functions>

</report>
